### ISSUE TITLE
Scrollbars appear in a weird place

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/paper-dialog-scrollable#32] opened 2016-01-14 15:45 UTC
They appear on top of what is supposed to be scrolled.

Code: https://github.com/kenchris/weneed/blob/master/app/elements/write-dialog/write-dialog.html

![scrollbars](https://cloud.githubusercontent.com/assets/1101339/12328963/344c1f4e-bade-11e5-9795-24eadde6fe12.png)

**Comment by kenchris** [comment] 2016-01-21 17:28
@valdrinkoshi

**Comment by valdrinkoshi** [comment] 2016-01-22 22:42
@kenchris can you provide a jsbin that reproduces the issue?
Looking at the code you provided, I suspect this is caused by the css you apply.

**Comment by valdrinkoshi** [comment] 2016-01-22 22:43
Oh, this can be reproduced with this jsbin http://jsbin.com/humawo/7/edit?html,output
Only chrome canary and chrome dev for android

**Comment by valdrinkoshi** [comment] 2016-01-23 03:39
Apparently this is caused by `box-shadow` applied to `paper-dialog`, in fact by setting to `none` fixes it (test it in chrome canary) http://jsbin.com/humawo/26/edit?html

cc @cdata

**Comment by valdrinkoshi** [comment] 2016-01-25 21:02
Seems like a bug of chrome http://jsbin.com/nudoru/5/edit?html,output
I've opened an issue on chromium https://code.google.com/p/chromium/issues/detail?id=581136
Closing this

**Closed as completed by valdrinkoshi** 2016-01-25 21:02 UTC
